import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import SearchHeader from "./components/SearchHeader";
import QueryClientContext from "./context/QueryClientContext";
import RecoilRootWrapper from "./context/RecoilRootWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <RecoilRootWrapper>
          <QueryClientContext>
            <SearchHeader />
            {children}
          </QueryClientContext>
        </RecoilRootWrapper>
      </body>
    </html>
  );
}
